# Generated by Django 6.0.3 on 2026-03-07 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_dislikes_job_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='interested_by',
            field=models.ManyToManyField(blank=True, related_name='interested_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
