# Generated by Django 6.0.3 on 2026-03-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('jobs', '0002_alter_job_options_job_dislikes_job_likes'),
        ('posts', '0002_post_dislikes'),
        ('services', '0003_alter_service_options_service_dislikes_service_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.job'),
        ),
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='services.service'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post'),
        ),
    ]
