# Generated by Django 6.0.3 on 2026-03-07 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AddField(
            model_name='service',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
