# Generated by Django 6.0.3 on 2026-03-07 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_options_service_dislikes_service_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='interested_by',
            field=models.ManyToManyField(blank=True, related_name='interested_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
